apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-patch
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-ingress-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift/app/
    repoURL: https://github.com/christianh814/ssa-test
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
